name: Release

on:
  push:
    branches: [ main ]


jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag: V1
        token: ${{ secrets.GITHUB_TOKEN }}
